// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsTkT2nwZtkoDYU1WbIDAOVWvRlFaY_s',
    appId: '1:1059872485754:web:c876abfb2b7e75c8faa6c3',
    messagingSenderId: '1059872485754',
    projectId: 'projek-uts-mobile-progamming',
    authDomain: 'projek-uts-mobile-progamming.firebaseapp.com',
    storageBucket: 'projek-uts-mobile-progamming.appspot.com',
    measurementId: 'G-HHFMLJXM2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6x_2ijIUWD-BH6YJUVz40i9MdMsbg_0',
    appId: '1:1059872485754:android:42937cc06fef1ee8faa6c3',
    messagingSenderId: '1059872485754',
    projectId: 'projek-uts-mobile-progamming',
    storageBucket: 'projek-uts-mobile-progamming.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHYGbIqSmvj5U9jGzASBBKE12i4UFpLs',
    appId: '1:1059872485754:ios:90131f0fd403f1e6faa6c3',
    messagingSenderId: '1059872485754',
    projectId: 'projek-uts-mobile-progamming',
    storageBucket: 'projek-uts-mobile-progamming.appspot.com',
    iosBundleId: 'com.example.projekUtsMobileProgamming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsHYGbIqSmvj5U9jGzASBBKE12i4UFpLs',
    appId: '1:1059872485754:ios:90131f0fd403f1e6faa6c3',
    messagingSenderId: '1059872485754',
    projectId: 'projek-uts-mobile-progamming',
    storageBucket: 'projek-uts-mobile-progamming.appspot.com',
    iosBundleId: 'com.example.projekUtsMobileProgamming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANsTkT2nwZtkoDYU1WbIDAOVWvRlFaY_s',
    appId: '1:1059872485754:web:577341e8e10418affaa6c3',
    messagingSenderId: '1059872485754',
    projectId: 'projek-uts-mobile-progamming',
    authDomain: 'projek-uts-mobile-progamming.firebaseapp.com',
    storageBucket: 'projek-uts-mobile-progamming.appspot.com',
    measurementId: 'G-D2G8LVB3VX',
  );
}
